# Dockerfile.chrome
FROM zenika/alpine-chrome

USER root
RUN apk add --no-cache font-noto-bengali fontconfig && fc-cache -f
USER chrome

# Add THESE exact flags
CMD [ \
    "--headless", \
    "--remote-debugging-address=0.0.0.0", \
    "--remote-debugging-port=9222", \
    "--remote-allow-origins=*", \
    "--no-sandbox", \
    "--disable-gpu", \
    "--disable-dev-shm-usage", \
    "about:blank" \
]
