// src/components/PreviewCanvas.tsx
'use client'
import { useRef, useState } from 'react'
import { useStore, useActiveTemplate } from '@/store/useStore'
import CardPreview from './CardPreview'
import { Download, ZoomIn, ZoomOut, Maximize2, Facebook, Share2 } from 'lucide-react'

export default function PreviewCanvas() {
  const { cardData, updatePhotoById, updateBlurRegion, removeBlurRegion } = useStore()
  const template = useActiveTemplate()
  const [exporting, setExporting] = useState(false)
  const [zoom, setZoom] = useState(100)
  const cardRef = useRef<HTMLDivElement>(null)
  
  const [postingFB, setPostingFB] = useState(false)
  const [fbPostUrl, setFbPostUrl] = useState<string | null>(null)

  const handleExport = async () => {
    setExporting(true)
    try {
      const { toPng } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return

      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400)) // Increased delay for layout/image settle

      const dataUrl = await toPng(el, {
        pixelRatio: 3,
        backgroundColor: '#ffffff',
        cacheBust: true, // Prevent stale images
      })
      
      const link = document.createElement('a')
      link.download = `${template.name.toLowerCase().replace(/\s+/g, '-')}.png`
      link.href = dataUrl
      link.click()
    } catch (err) {
      console.error('Export failed:', err)
    } finally {
      setExporting(false)
    }
  }

  const handleShare = async () => {
    setExporting(true)
    try {
      const { toBlob } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return

      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400))

      const blob = await toBlob(el, {
        pixelRatio: 3,
        backgroundColor: '#ffffff',
        cacheBust: true,
      })
      if (!blob) throw new Error('Share capture failed')

      const file = new File([blob], 'photocard.png', { type: 'image/png' })

      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'Photocard Studio',
          text: `Check out this photocard: ${cardData.headline}`,
        })
      } else {
        // Fallback for desktop/unsupported browsers
        const dataUrl = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.download = `${template.name.toLowerCase().replace(/\s+/g, '-')}.png`
        link.href = dataUrl
        link.click()
        alert('Sharing directly is not supported on this browser. The image has been downloaded—you can now upload it to Facebook manually.')
      }
    } catch (err) {
      console.error('Share failed:', err)
    } finally {
      setExporting(false)
    }
  }

  const handlePostToFacebook = async () => {
    setPostingFB(true)
    try {
      const { toBlob } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return
      
      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400))

      const blob = await toBlob(el, { 
        pixelRatio: 3,
        cacheBust: true
      })
      if (!blob) throw new Error('Canvas capture failed')

      const formData = new FormData()
      formData.append('file', blob, 'post.png')
      formData.append('caption', `New Photocard: ${cardData.headline}\n\nGenerated by Photocard Studio`)

      const res = await fetch('/api/facebook/post', {
        method: 'POST',
        body: formData
      })

      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Upload failed')

      setFbPostUrl(data.url)
      alert('Success! Posted directly to your Facebook Page.')
    } catch (err: any) {
      console.error(err)
      alert('Facebook Post Failed: ' + err.message)
    } finally {
      setPostingFB(false)
    }
  }

  return (
    <div className="flex-1 flex flex-col bg-[#0d0d0d] min-w-0 overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-3 md:px-5 py-2 md:py-3 gap-2 border-b border-zinc-800">
        <div className="flex items-center gap-1">
          <button
            onClick={() => setZoom(z => Math.max(40, z - 10))}
            className="w-7 h-7 flex items-center justify-center rounded text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors"
          >
            <ZoomOut size={14} />
          </button>
          <span className="text-[10px] md:text-xs text-zinc-500 w-8 md:w-10 text-center">{zoom}%</span>
          <button
            onClick={() => setZoom(z => Math.min(150, z + 10))}
            className="w-7 h-7 flex items-center justify-center rounded text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors"
          >
            <ZoomIn size={14} />
          </button>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-[9px] md:text-[11px] text-zinc-600 hidden xs:inline">1080 × 1080 px</span>
          <button
            onClick={handlePostToFacebook}
            disabled={postingFB}
            className={`flex items-center gap-1.5 px-3 md:px-4 py-1.5 rounded disabled:opacity-50 text-white text-[10px] md:text-xs font-medium transition-all ${
              fbPostUrl ? 'bg-green-600' : 'bg-[#1877F2] hover:bg-[#166fe5]'
            }`}
          >
            <Facebook size={12} className={postingFB ? 'animate-pulse' : ''} />
            <span className="whitespace-nowrap">
              {postingFB ? 'Posting...' : fbPostUrl ? 'Posted!' : 'Post to Page'}
            </span>
          </button>
          <button
            onClick={handleShare}
            disabled={exporting}
            className="flex items-center gap-1.5 px-3 md:px-4 py-1.5 rounded bg-zinc-800 hover:bg-zinc-700 disabled:opacity-50 text-white text-[10px] md:text-xs font-medium transition-colors border border-zinc-700"
          >
            <Share2 size={12} className="md:w-[13px] md:h-[13px]" />
            <span className="whitespace-nowrap text-zinc-300">Share</span>
          </button>
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex items-center gap-1.5 px-3 md:px-4 py-1.5 rounded bg-zinc-800 hover:bg-zinc-700 disabled:opacity-50 text-white text-[10px] md:text-xs font-medium transition-colors border border-zinc-700"
          >
            <Download size={12} className="md:w-[13px] md:h-[13px]" />
            {exporting ? '...' : (
              <span className="whitespace-nowrap text-zinc-300">PNG</span>
            )}
          </button>
        </div>
      </div>

      {/* Canvas area */}
      <div className="flex-1 overflow-auto flex items-center justify-center p-4 md:p-8"
        style={{ backgroundImage: 'radial-gradient(circle, #1a1a1a 1px, transparent 1px)', backgroundSize: '20px 20px' }}
      >
        <div
          style={{
            width: `${zoom}%`,
            maxWidth: 600,
            minWidth: 200,
            transition: 'width 0.2s',
          }}
        >
          <CardPreview 
            key={`${cardData.headline}-${cardData.photos[0]?.src || 'no-photo'}`}
            ref={cardRef}
            template={template} 
            cardData={cardData} 
            forExport={exporting}
            onPhotoChange={(id, patch) => updatePhotoById(id, patch)}
            onBlurChange={(id, patch) => updateBlurRegion(id, patch)}
            onBlurRemove={(id) => removeBlurRegion(id)}
          />
        </div>
      </div>

      {/* Bottom info bar */}
      <div className="px-5 py-2 border-t border-zinc-800 flex items-center justify-between">
        <span className="text-[10px] text-zinc-600">
          Template: <span className="text-zinc-400">{template.name}</span>
          {' · '}
          Layout: <span className="text-zinc-400">{template.layout}</span>
          {' · '}
          Photos: <span className="text-zinc-400">{template.photoCount}</span>
        </span>
        <span className="text-[10px] text-zinc-600">Output: 3240 × 3240 px (3× scale)</span>
      </div>
    </div>
  )
}
