// src/components/PreviewCanvas.tsx
'use client'
import { useRef, useState } from 'react'
import { useStore, useActiveTemplate } from '@/store/useStore'
import CardPreview from './CardPreview'
import { Download, Share2, ChevronDown, Undo, Redo, Trash2, Settings } from 'lucide-react'

export default function PreviewCanvas() {
  const { cardData, updatePhotoById, updateBlurRegion, removeBlurRegion, updateCustomLayer, removeCustomLayer } = useStore()
  const template = useActiveTemplate()
  const [exporting, setExporting] = useState(false)
  const [zoom, setZoom] = useState(100)
  const cardRef = useRef<HTMLDivElement>(null)
  
  const [postingFB, setPostingFB] = useState(false)
  const [fbPostUrl, setFbPostUrl] = useState<string | null>(null)

  const handleExport = async () => {
    setExporting(true)
    try {
      const { toPng } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return

      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400)) // Increased delay for layout/image settle

      const dataUrl = await toPng(el, {
        pixelRatio: 3,
        backgroundColor: '#ffffff',
        cacheBust: true, // Prevent stale images
      })
      
      const link = document.createElement('a')
      link.download = `${template.name.toLowerCase().replace(/\s+/g, '-')}.png`
      link.href = dataUrl
      link.click()
    } catch (err) {
      console.error('Export failed:', err)
    } finally {
      setExporting(false)
    }
  }

  const handleShare = async () => {
    setExporting(true)
    try {
      const { toBlob } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return

      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400))

      const blob = await toBlob(el, {
        pixelRatio: 3,
        backgroundColor: '#ffffff',
        cacheBust: true,
      })
      if (!blob) throw new Error('Share capture failed')

      const file = new File([blob], 'photocard.png', { type: 'image/png' })

      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'Photocard Studio',
          text: `Check out this photocard: ${cardData.headline}`,
        })
      } else {
        // Fallback for desktop/unsupported browsers
        const dataUrl = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.download = `${template.name.toLowerCase().replace(/\s+/g, '-')}.png`
        link.href = dataUrl
        link.click()
        alert('Sharing directly is not supported on this browser. The image has been downloaded—you can now upload it to Facebook manually.')
      }
    } catch (err) {
      console.error('Share failed:', err)
    } finally {
      setExporting(false)
    }
  }

  const handlePostToFacebook = async () => {
    setPostingFB(true)
    try {
      const { toBlob } = await import('html-to-image')
      const el = cardRef.current
      if (!el) return
      
      await document.fonts.ready
      await new Promise(r => setTimeout(r, 400))

      const blob = await toBlob(el, { 
        pixelRatio: 3,
        cacheBust: true
      })
      if (!blob) throw new Error('Canvas capture failed')

      const formData = new FormData()
      formData.append('file', blob, 'post.png')
      formData.append('caption', `New Photocard: ${cardData.headline}\n\nGenerated by Photocard Studio`)

      const res = await fetch('/api/facebook/post', {
        method: 'POST',
        body: formData
      })

      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Upload failed')

      setFbPostUrl(data.url)
      alert('Success! Posted directly to your Facebook Page.')
    } catch (err: any) {
      console.error(err)
      alert('Facebook Post Failed: ' + err.message)
    } finally {
      setPostingFB(false)
    }
  }

  return (
    <div className="flex-1 flex flex-col bg-[#14141A] min-w-0 overflow-hidden border-t border-zinc-800/50 md:border-none">
      {/* Top Action Bar */}
      <div className="flex items-center justify-between px-4 md:px-6 py-3 border-b border-zinc-800/50 bg-[#1E1E24]">
        {/* Left: Project Name */}
        <div className="flex items-center gap-2 cursor-pointer hover:bg-zinc-800/50 p-1.5 rounded transition-colors">
          <span className="text-white font-medium text-xs md:text-sm tracking-wide">newscards.xyz</span>
          <ChevronDown size={14} className="text-zinc-500" />
        </div>

        {/* Center: Actions */}
        <div className="hidden md:flex items-center gap-4 absolute left-1/2 -translate-x-1/2">
          <div className="flex items-center gap-2 text-zinc-400">
            <button className="p-1.5 hover:text-white hover:bg-zinc-700/50 rounded transition-colors"><Undo size={16} /></button>
            <button className="p-1.5 hover:text-white hover:bg-zinc-700/50 rounded transition-colors"><Redo size={16} /></button>
            <div className="w-px h-4 bg-zinc-700 mx-1"></div>
            <button className="p-1.5 hover:text-red-400 hover:bg-zinc-700/50 rounded transition-colors"><Trash2 size={16} /></button>
          </div>
          <button className="bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs px-6 py-1.5 rounded-md transition-colors shadow-[0_0_15px_rgba(37,99,235,0.3)]">
            Save
          </button>
        </div>

        {/* Right: Export/Share */}
        <div className="flex items-center gap-3">
          <button className="hidden md:flex p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-700/50 rounded transition-colors">
            <Settings size={16} />
          </button>
          <button
            onClick={handleShare}
            disabled={exporting}
            className="flex items-center gap-2 px-3 md:px-4 py-1.5 rounded-lg border border-zinc-700 hover:bg-zinc-800 disabled:opacity-50 text-white text-xs font-medium transition-colors"
          >
            <Share2 size={14} />
            <span className="hidden sm:inline">Share</span>
          </button>
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex items-center gap-2 px-3 md:px-4 py-1.5 rounded-lg bg-zinc-100 hover:bg-white disabled:opacity-50 text-zinc-900 text-xs font-bold transition-colors"
          >
            <Download size={14} />
            {exporting ? '...' : (
              <span>Export</span>
            )}
          </button>
        </div>
      </div>

      {/* Canvas area */}
      <div className="flex-1 overflow-auto flex items-center justify-center p-4 md:p-8"
        style={{ backgroundImage: 'radial-gradient(circle, #1a1a1a 1px, transparent 1px)', backgroundSize: '20px 20px' }}
      >
        <div
          style={{
            width: `${zoom}%`,
            maxWidth: 600,
            minWidth: 200,
            transition: 'width 0.2s',
          }}
        >
          <CardPreview 
            key={`${cardData.headline}-${cardData.photos[0]?.src || 'no-photo'}`}
            ref={cardRef}
            template={template} 
            cardData={cardData} 
            forExport={exporting}
            onPhotoChange={(id, patch) => updatePhotoById(id, patch)}
            onBlurChange={(id, patch) => updateBlurRegion(id, patch)}
            onBlurRemove={(id) => removeBlurRegion(id)}
            onCustomLayerChange={(id, patch) => updateCustomLayer(id, patch)}
            onCustomLayerRemove={(id) => removeCustomLayer(id)}
          />
        </div>
      </div>

      <div className="px-5 py-2.5 border-t border-zinc-800/50 flex items-center justify-between bg-[#1E1E24]">
        <div className="flex items-center gap-3">
          <span className="text-[11px] font-medium text-zinc-400 bg-zinc-800/50 px-2 py-1 rounded">
            {template.layout}
          </span>
          <span className="text-[11px] text-zinc-500">
            {template.photoCount} Photo{template.photoCount > 1 ? 's' : ''}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setZoom(z => Math.max(40, z - 10))}
            className="text-zinc-500 hover:text-white"
          >
            -
          </button>
          <span className="text-[10px] text-zinc-500 w-8 text-center">{zoom}%</span>
          <button
            onClick={() => setZoom(z => Math.min(150, z + 10))}
            className="text-zinc-500 hover:text-white"
          >
            +
          </button>
        </div>
      </div>
    </div>
  )
}
