from fastapi import APIRouter, UploadFile, File
from PIL import Image
from io import BytesIO
from services.shield import shield_service
from exceptions import AppException
from utils.logging import logger

router = APIRouter()

@router.post("/")
async def verify_photocard(file: UploadFile = File(...)):
    """
    Verifies the authenticity of a news card by extracting the invisible shield ID.
    """
    try:
        # Read uploaded image
        contents = await file.read()
        image = Image.open(BytesIO(contents)).convert("RGB")
        
        # Extract invisible shield ID
        shield_id = shield_service.extract_shield(image)
        
        if not shield_id:
            logger.warning("Verification failed: No shield detected")
            return {
                "status": "unverified",
                "message": "No authenticity shield detected. This image might be tampered with or not generated by our system."
            }
            
        # 3. Check Database for this Shield ID
        from services.photocard import photocard_service
        try:
            db_record = photocard_service.get_by_shield_id(shield_id)
            if db_record:
                logger.info(f"Verification successful: Shield ID {shield_id} matched in DB")
                return {
                    "status": "verified",
                    "shield_id": shield_id,
                    "original_data": {
                        "headline": db_record.get("headline"),
                        "created_at": db_record.get("created_at")
                    },
                    "message": "Authenticity shield verified. This is a genuine, untampered NewsCards asset."
                }
        except:
            pass

        logger.info(f"Verification partial: Shield ID {shield_id} detected but not found in DB")
        return {
            "status": "partial",
            "shield_id": shield_id,
            "message": "Authenticity shield detected, but record not found in database. The image structure is genuine, but the original data cannot be verified."
        }
    except Exception as e:
        logger.error(f"Verification process error: {e}")
        raise AppException(f"Verification failed: {str(e)}")
